2025-03-17 15:54:21,998 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_155421-nnd569ie\logs\debug.log
2025-03-17 15:54:22,000 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_155421-nnd569ie\logs\debug-internal.log
2025-03-17 15:54:22,001 INFO    MainThread:3816 [wandb_init.py:init():761] calling init triggers
2025-03-17 15:54:22,002 INFO    MainThread:3816 [wandb_init.py:init():766] wandb.init called with sweep_config: {'L2_lamb': 0.0005, 'activation_f': 'relu', 'batch_size': 64, 'epochs': 5, 'init_mode': 'xavier', 'learning_rate': 0.0001, 'num_hidden': 3, 'num_neurons': 64, 'optimizer': 'nestorov'}
config: {'_wandb': {}}
2025-03-17 15:54:22,004 INFO    MainThread:3816 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 15:54:22,005 ERROR   MainThread:3816 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:22,479 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 15:54:22,481 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 15:54:22,483 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:22,487 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:23,782 INFO    MainThread:3816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-17 15:54:23,785 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:23,794 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:24,059 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_155424-nnd569ie\logs\debug.log
2025-03-17 15:54:24,062 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_155424-nnd569ie\logs\debug-internal.log
2025-03-17 15:54:24,064 INFO    MainThread:3816 [wandb_init.py:init():761] calling init triggers
2025-03-17 15:54:24,065 INFO    MainThread:3816 [wandb_init.py:init():766] wandb.init called with sweep_config: {'L2_lamb': 0.0005, 'activation_f': 'relu', 'batch_size': 64, 'epochs': 5, 'init_mode': 'xavier', 'learning_rate': 0.0001, 'num_hidden': 3, 'num_neurons': 64, 'optimizer': 'nestorov'}
config: {'_wandb': {}}
2025-03-17 15:54:24,067 INFO    MainThread:3816 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 15:54:24,068 ERROR   MainThread:3816 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:24,528 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 15:54:24,529 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 15:54:24,530 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:54:24,534 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:58:11,395 INFO    MainThread:3816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-17 15:58:11,399 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:58:11,404 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:58:11,640 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_155811-nnd569ie\logs\debug.log
2025-03-17 15:58:11,647 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_155811-nnd569ie\logs\debug-internal.log
2025-03-17 15:58:11,649 INFO    MainThread:3816 [wandb_init.py:init():761] calling init triggers
2025-03-17 15:58:11,651 INFO    MainThread:3816 [wandb_init.py:init():766] wandb.init called with sweep_config: {'L2_lamb': 0.0005, 'activation_f': 'relu', 'batch_size': 64, 'epochs': 5, 'init_mode': 'xavier', 'learning_rate': 0.0001, 'num_hidden': 3, 'num_neurons': 64, 'optimizer': 'nestorov'}
config: {'_wandb': {}}
2025-03-17 15:58:11,654 INFO    MainThread:3816 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 15:58:11,656 ERROR   MainThread:3816 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:58:12,163 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 15:58:12,165 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 15:58:12,168 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 15:58:12,171 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:00:35,871 INFO    MainThread:3816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-17 16:00:35,874 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:00:35,883 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:00:36,140 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_160036-nnd569ie\logs\debug.log
2025-03-17 16:00:36,143 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_160036-nnd569ie\logs\debug-internal.log
2025-03-17 16:00:36,145 INFO    MainThread:3816 [wandb_init.py:init():761] calling init triggers
2025-03-17 16:00:36,147 INFO    MainThread:3816 [wandb_init.py:init():766] wandb.init called with sweep_config: {'L2_lamb': 0.0005, 'activation_f': 'relu', 'batch_size': 64, 'epochs': 5, 'init_mode': 'xavier', 'learning_rate': 0.0001, 'num_hidden': 3, 'num_neurons': 64, 'optimizer': 'nestorov'}
config: {'_wandb': {}}
2025-03-17 16:00:36,150 INFO    MainThread:3816 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 16:00:36,151 ERROR   MainThread:3816 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:00:36,682 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 16:00:36,683 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 16:00:36,692 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:00:36,697 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:02,515 INFO    MainThread:3816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-17 16:01:02,518 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:02,526 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:03,006 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_160102-nnd569ie\logs\debug.log
2025-03-17 16:01:03,009 INFO    MainThread:3816 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment_1\wandb\run-20250317_160102-nnd569ie\logs\debug-internal.log
2025-03-17 16:01:03,011 INFO    MainThread:3816 [wandb_init.py:init():761] calling init triggers
2025-03-17 16:01:03,013 INFO    MainThread:3816 [wandb_init.py:init():766] wandb.init called with sweep_config: {'L2_lamb': 0.0005, 'activation_f': 'relu', 'batch_size': 64, 'epochs': 5, 'init_mode': 'xavier', 'learning_rate': 0.0001, 'num_hidden': 3, 'num_neurons': 64, 'optimizer': 'nestorov'}
config: {'_wandb': {}}
2025-03-17 16:01:03,014 INFO    MainThread:3816 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 16:01:03,017 ERROR   MainThread:3816 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:04,007 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 16:01:04,011 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 16:01:04,015 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:04,031 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:09,839 INFO    MainThread:3816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-17 16:01:09,842 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:09,851 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:10,080 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 16:01:10,081 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 16:01:10,083 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:10,088 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:21,086 INFO    MainThread:3816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-17 16:01:21,090 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:21,098 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:21,323 INFO    MainThread:3816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 16:01:21,324 INFO    MainThread:3816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 16:01:21,325 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-17 16:01:21,331 ERROR   MainThread:3816 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\IPython\core\events.py", line 82, in trigger
    func(*args, **kwargs)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Dell\Desktop\Courses\Sem_VIII\DA6401\DA6401-Introduction-to-Deep-Learning\Assignment1\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
